config/routes.rb
SimpleFeed::Application.routes.draw do
  root to: "sessions#new"
  resources :users
  resources :feeds do
    resources :entries, only: [:update, :destroy]
  end
  resource :session
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id            :integer          not null, primary key
#  username      :text             not null
#  password_hash :text             not null
#  session_token :text
#  created_at    :datetime
#  updated_at    :datetime
#

class User < ActiveRecord::Base
  validates :username, :password_hash, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true}
  #before_validation :ensure_session_token

  attr_reader :password

  has_many :feeds

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  # def ensure_session_token
  #   self.session_token ||=
  # end

  def password=(plaintext_password)
    @password = plaintext_password
    self.password_hash = BCrypt::Password.create(plaintext_password)
  end

  def is_password?(plaintext_password)
    BCrypt::Password.new(self.password_hash).is_password?(plaintext_password)
  end

  #return our user if we can find them & pw matches, else return nil
  def self.find_by_credentials(params)
    user = User.find_by(username: params[:username])
    return user if user && user.is_password?(params[:password])
    nil
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new()
    render :new
  end

  def index
    if logged_in?
      respond_to do |format|
        format.html { redirect_to user_url(current_user) }
        format.json { render :json => current_user.to_json(:only => [:username, :id]) }
      end
    else
      redirect_to "/"
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    if !logged_in?
      flash[:errors] = ["You must be logged in to view that!"]
      redirect_to "/"
    else
      @user = current_user
      @feeds = @user.feeds
      @feeds.each { |f| f.reload }

      respond_to do |format|
        format.html { render :feed_loading_page }
        format.json { render :json => @user.as_json}
      end
    end

  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/feed_loading_page.html.erb
<div class="feed-loading-page">

  <h1 class="loading-text">Please wait while we load your RSS feeds...</h1>
  <h3 class="loading-text"><div class="glyphicon glyphicon-refresh spin"></div></h3>
  <h2 class="loading-text">:^)</h2>

</div>

app/views/users/new.html.erb
<div class="user-page">

  <a href="https://github.com/strong-code"><img style="position: absolute; top: 0; left: 0; border: 0;" src="https://camo.githubusercontent.com/567c3a48d796e2fc06ea80409cc9dd82bf714434/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f6461726b626c75655f3132313632312e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_left_darkblue_121621.png"></a>

  <h1>Sign Up</h1>
    <form action="<%= users_url %>" method="POST">
      <div class="form-group">

      <%= csrf_token %>

      <label>Username
        <input class="form-control" type="text" name="user[username]" value="<%= @user.username %>">
      <label>

      <br>

      <label>Password
        <input class="form-control" type="password" name="user[password]" value="<%= @user.password %>">
      <label>

      <br>

      <p><button type="submit" id="create-account" class="btn btn-default">Create Account</button></p>
    </div>
  </form>

  <span class="alternative-user-action">Already have an account? <%= link_to "Log In", new_session_url %></span>
</div>

app/views/users/show.html.erb
<div class='col-xs-5 col-xs-offset-1'>
  <h1>Hello, <%= @user.username%></h1>
</div>

  <header class="row"></header>

  <div class='col-xs-5' id='main-sidebar'>
    <form action="<%= feeds_url %>" method="POST" id="new-feed-form">
        <div class="input-group">
          <%= csrf_token %>
          <input type="text" class="form-control" name="feed[url]" placeholder="yourfeedurl.com/rss">
          <span class="input-group-btn">
            <button type="submit" class="btn btn-primary" id="submit-new-feed-btn">
              <span class="glyphicon glyphicon-plus-sign" id="submit-new-feed-icon"></span>  Add Feed
            </button>
          </span>
      </div>
    </form>

    <br>
    <div id="feed-list">
      <ul>
        <% @feeds.reverse.each do |feed| %>
          <div class="feed-list-entry">
              <h4 class="feed-list-title"><%= feed.title %>
                <a data-method="patch" href="<%= feed_url(feed) %>"><span data-id="<%= feed.id %>" class="glyphicon glyphicon-refresh"></span></a>
                <a data-method="delete" href="<%= feed_url(feed) %>"><span data-id="<%= feed.id %>" class="glyphicon glyphicon-trash"></span></a>
              </h4>
              <% if feed.description %>
                <%= feed.description[0..110]%><% if feed.description.length > 110 %>... <%end%>
              <% end %>
          </div>
          <br>
        <% end %>
      </ul>
    </div>

  </div>

  <% if @feeds.empty? %>
    <div class="col-xs-6">
      <div class="alert alert-info">
        <span class="glyphicon glyphicon-bell"></span>
        It seems you don't have any feeds yet :( Try adding one by supplying a valid RSS/Atom URL to get started.
      </div>
    </div>
  <% else %>
    <div class="col-xs-6" id="current-feed-entries">
      <% @feeds.reverse.each do |feed| %>
        <h3><%= feed.title %></h3>
          <% feed.entries.reverse.each do |entry| %>
            <% begin %>
              <div><a href="<%= CGI.unescapeHTML(entry.link) %>"><%= CGI.unescapeHTML(entry.title) %></a></div>
            <% rescue => e %>
              <div><a href="<%= entry.link.force_encoding("ASCII-8BIT") %>"><%= entry.title.force_encoding("ASCII-8BIT") %></a></div>
            <% end %>
          <% end %>
      <% end %>
    </div>
  <% end %>

  <div class="row"></div>

  <footer class='col-xs-4 col-xs-offset-1'>
    <%= link_to "Log Out", session_url, method: :delete%>
  </footer>


<script>
  $(function() {
    $('.glyphicon-refresh, .glyphicon-trash').on('click', function(e) {
      $(e.currentTarget).toggleClass("spin");
    });
    $('.glyphicon-trash').on('click', function(e) {
      $(e.currentTarget).toggleClass("glyphicon-trash");
      $(e.currentTarget).toggleClass("glyphicon-cog");
    });
    $('#submit-new-feed-btn').on('click', function() {
      $('#submit-new-feed-icon').toggleClass("spin");
      $('#submit-new-feed-icon').toggleClass("glyphicon-plus-sign");
      $('#submit-new-feed-icon').toggleClass("glyphicon-cog");
    })
  });
</script>